/*
** ###################################################################
**
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**
**     Filename  : TIMER.C
**
**     Project   : vph1
** 
**     Processor : MC68HC908GP32CFB
**
**     Beantype  : TimerInt
**
**     Version   : Bean 02.055, Driver 01.10, CPU db: 2.87.041
**
**     Compiler  : Metrowerks HC08 C Compiler V-5.0.13
**
**     Date/Time : 05/02/2007, 19:44
**
**     Abstract  :
**
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload 
**         register or timer-overflow interrupt (of free running counter).
**
**     Settings  :
**
**         Timer name                  : TIM2 (16-bit)
**         Compare name                : TIM20
**         Counter shared              : No
**
**         High-speed CPU mode
**             Prescaler               : divide-by-1
**             Clock                   : 2457600 Hz
**           Initial period/frequency
**             Xtal ticks              : 33
**             microseconds            : 1000
**             milliseconds            : 1
**             seconds (real)          : 0.0009998
**             Hz                      : 1000
**             kHz                     : 1
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : T2CNT     [44]
**              Mode                   : T2SC      [43]
**              Run                    : T2SC      [43]
**              Prescaler              : T2SC      [43]
**
**         Compare registers
**              Compare                : T2CH0     [49]
**
**         Flip-flop registers
**              Mode                   : T2SC0     [48]
**
**     Contents  :
**
**         No public methods
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2002
**
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
**
** ###################################################################
*/


/* MODULE TIMER. */

#include "Events.h"
#include "PE_Error.h"
#include "TIMER.h"

#pragma MESSAGE DISABLE C2705          /* WARNING C2705: Possible loss of data */
#pragma MESSAGE DISABLE C5919          /* WARNING C5919: Conversion of floating to unsigned integral */



/*
** ===================================================================
**     Method      :  TIMER_SetCV (bean TimerInt)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
static void SetCV(word Val)
{
  T2CH0H = (*(TWREG*)&Val).b.high;     /* Store given value to the compare register */
  T2MODH = (*(TWREG*)&Val).b.high;     /* and to the modulo register */
  T2CH0L = (*(TWREG*)&Val).b.low;
  T2MODL = (*(TWREG*)&Val).b.low;
}

/*
** ===================================================================
**     Method      :  TIMER_SetPV (bean TimerInt)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
static void SetPV(byte Val)
{
  T2SC_PS = Val;                       /* Store given value to the prescaler */
  T2SC_TRST = 1;                       /* Reset counter */
}

/*
** ===================================================================
**     Method      :  TIMER_Init (bean TimerInt)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
void TIMER_Init(void)
{
  T2SC = 48;                           /* Set up (output) compare mode */
  T2SC0 = 80;
  SetCV(2457);                         /* Store appropriate value to the compare register according to the selected high speed CPU mode */
  SetPV(0);                            /* Set prescaler register according to the selected high speed CPU mode */
  T2SC_TSTOP = 0;                      /* Run counter */
}

/*
** ===================================================================
**     Method      :  TIMER_Interrupt (bean TimerInt)
**
**     Description :
**         This method is internal. It is used by Processor Expert
**         only.
** ===================================================================
*/
__interrupt void TIMER_Interrupt(void)
{
  T2SC0_CHxF = 0;                      /* Reset interrupt request flag */
  TIMER_OnInterrupt();                 /* Invoke user event */
}


/* END TIMER. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 02.89 for 
**     the Motorola HC08 series of microcontrollers.
**
** ###################################################################
*/
